export default function Head() {
  return (
    <>
      <title>Live Music Audio Chat</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by IronSoul" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
